# Phase II design

## Simon's two-stage design 

Simon's two-stage design is used to minimize the expected sample size when the true response is less than some pre-determined uninterested level $\pi_0$ [@simon1989optimal]. 

The null hypothesis is that $H_0: \pi = \pi_0$ and the alternative hypothesis is $H_1: \pi = \pi_1$ where $pi_1$ is some desirable level that warrant further development. Suppose the Type I and Type II errors are $\alpha$ and $\beta$. 

Let $n_1$ patients be given treatment in the first stage. If $r_1$ or less respond or more than $r$ respond, stop stage 1. Otherwise, let $n_2$ patients be given treatment in the second stage. $n = n_1 + n_2$.

Suppose $X_1 \sim Bin(n_1, \pi)$ and $X_2 \sim Bin(n_2, \pi)$. We declare the new drug a

+ Failure if 
$\xi_F = X_1 \leq r_1 \text{ OR } \{X_1 > r_1 \text { AND } X_1 + X_2 \leq r \}$
+ Success if $\xi_S = \{X_1 > r_1 \text{ AND } X_1 + X_2 > r \}$

Therefore, 
$$
P(\xi_F \mid \pi \leq \pi_0) \leq \alpha,  \quad P(\xi_S \mid \pi \geq \pi_1) \geq 1- \beta
$$

Moreover, we have 
$$\begin{aligned}
P(\xi_S \mid \pi) & = \sum_{m_1 > r_1, m_1 + m_2 > r} P(X_1 = m_1\mid \pi)P(X_2 = m_2\mid \pi) \\
P(\xi_F \mid \pi) & = 1- P(\xi_S \mid \pi)
\end{aligned}$$

The expected sample size $EN(\pi_0)$ is given by 
$$
n_1\left[P(X_1 \leq r_1\mid \pi = \pi_0) + P(X_1 > r\mid \pi = \pi_0) \right] + nP(r_1 + 1 \leq X_1 \leq r \mid \pi = \pi_0)
$$
The probability of early termination is $PET(\pi_0) = P(X_1 \leq r_1 \text{ OR } X_1 >r\mid \pi = \pi_0)$.  

There are several choices to select $(r_1, n_1, r, n)$: 

+ **Optimal design**: the one has the smallest expected sample size when $\pi = \pi_0$.
+ **Minimax design**: the one has the smallest total sample size for the whole trial when $\pi = \pi_0$. 
+ **Adimssible design**: compromise the minimax and the optimal design. [@jung2004admissible]

```{r}
library(clinfun)
ph2simon(pu = 0.2, pa = 0.4, ep1 = 0.1, ep2 = 0.2)

library(ph2mult)
binom.design(type = "admissible", p0 = 0.15, p1 = 0.3, 
             signif.level = 0.05, power.level = 0.9)
```



